CMakeLists.txt, apps/yitrace.cpp, apps/ytrace.cpp, yocto/ygl.cpp, yocto/ygl.h, yocto/yglio.cpp, yocto/yglio.h
Support for loading, saving and parsing volumetric data.
=> Added volume1f support

apps/yitrace.cpp, yocto/ygl.cpp, yocto/ygl.h
Still some hacks (marked with @Hack) to clean up, but the code works and performs correct volume rendering.
=> Implemented trace_path_volume and added functions for volume rendering 

yocto/yglio.cpp
=> windows float

yocto/ygl.cpp, yocto/ygl.h, yocto/yglio.cpp
=> Split mesh data and fv-mesh data

apps/yglutils.cpp, apps/yglutils.h, apps/yimproc.cpp, apps/yimview.cpp, apps/yitrace.cpp, apps/ysceneui.h, apps/yview.cpp, yocto/ygl.cpp, yocto/ygl.h, yocto/yglio.cpp
=> yimview allows to load and save image and drag and drop. 

apps/yitrace.cpp, apps/yscnproc.cpp, apps/ytrace.cpp, apps/yview.cpp, yocto/ygl.h, yocto/yglio.cpp, yocto/yglio.h
Switched to using unique_ptr in IO and apps. Should probably switch to returning unique_ptr everywhere when things are created.
=> Using unique_ptr in IO and apps.

apps/yglutils.cpp, apps/yglutils.h, apps/yimview.cpp, apps/yitrace.cpp, apps/yview.cpp
Added typed objects for OpenGL.
=> Gl typed opbjects

apps/yglutils.cpp, apps/yglutils.h, apps/yimproc.cpp, apps/yimview.cpp, apps/yitrace.cpp, apps/ysceneui.h, apps/yview.cpp, yocto/ygl.cpp, yocto/ygl.h, yocto/yglio.cpp
Using a trivial struct for image and volume access.
=> Image and volume use a trivial struct.

yocto/ygl.h, yocto/yglio.cpp, yocto/yglio.h
Math is now using templates more pervasively.
=> Math uses generic templates more pervasively

yocto/ext/happly.h, yocto/ygl.cpp, yocto/ygl.h, yocto/yglio.cpp, yocto/yglio.h
Try to integrate the happy to see if it is easier to use than our own. We leave the code of our own parser to see which one scaled better.
=> Integrate the happy library.

CMakeLists.txt, yocto/yglio.cpp
Fixed all compilation issue on C++14. Removed experimental C++17 compilation since it is not stable on OsX.
=> Cpp14 only

tests/run-tests/test-ytrace.sh, yocto/ygl.cpp, yocto/ygl.h
Made sure that calls are deterministic in trace_XXX by enforsing order of execution and using internal buffers,
=> Deterministic calls in tracing

apps/yglutils.cpp, apps/yview.cpp, scripts/scenes-view.sh, yocto/ygl.cpp, yocto/ygl.h, yocto/yglio.cpp
=> Better missing camera default

CMakeLists.txt, tests/volume-models-al.json, tests/volume1-al.json, tests/volume2-al.json, yocto/yocto_sceneio.cpp, yocto/yocto_trace.cpp, yocto/yocto_trace.h
Volumetric path tracing implementation and tests.
=> Volume path

tests/refractive-al.json, yocto/yocto_trace.cpp
Implementation of rough refraction as described in Walter07 and general brdf code cleanup.
[Walter07] [https://www.cs.cornell.edu/~srm/publications/EGSR07-btdf.pdf](https://www.cs.cornell.edu/~srm/publications/EGSR07-btdf.pdf)
=> Rough refraction

yocto/yocto_trace.cpp
This commit also fix compilation errors raised when #define YOCTO_TRACE_THINSHEET 1
=> rough refraction in YOCTO_TRACE_THINSHEET define

yocto/yocto_trace.cpp
Matches pbrt for isotropic volumes.
=> Volume implementation inside path tracer

yocto/yocto_shape.cpp, yocto/yocto_shape.h
Build adjacency between each vertex and its adjacent **vertices**, sorted counter-clockwise.
Also build adjacency between each vertex and its adjacent **faces**, sorted counter-clockwise.
There's code duplication, the two functions differ for one line.
=> adjacency functions

libs/yocto/yocto_mesh.cpp
=> Compilation fix

libs/yocto_gui/yocto_gui.cpp, libs/yocto_gui/yocto_gui.h
Also, some changes to allow for initializing empty textures.
=> Support for cubemaps and framebuffers in yocto_gui (WIP)

libs/yocto/yocto_modelio.cpp, libs/yocto/yocto_sceneio.cpp
=> Fix bugs in OBJ output

libs/yocto/yocto_math.h
=> Small math improvements (#1415)
